//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePaperWeb.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<printandsubrate> printandsubrates { get; set; }
        public virtual DbSet<subscriber_address> subscriber_address { get; set; }
        public virtual DbSet<subscriber_epaper> subscriber_epaper { get; set; }
        public virtual DbSet<subscriber_print> subscriber_print { get; set; }
        public virtual DbSet<subscriber_tranx> subscriber_tranx { get; set; }
        public virtual DbSet<subscriber> subscribers { get; set; }
    }
}
