//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePaperWeb.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class euser
    {
        public int recid { get; set; }
        public string email { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string password { get; set; }
        public string token { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string province { get; set; }
        public Nullable<int> zip { get; set; }
        public string country { get; set; }
        public System.DateTime subscriptionStart { get; set; }
        public System.DateTime subscriptionEnd { get; set; }
        public bool active { get; set; }
        public bool newsletter { get; set; }
        public decimal cardAmount { get; set; }
        public string cardType { get; set; }
        public string cardOwnerName { get; set; }
        public string orderId { get; set; }
        public string secretQuestion { get; set; }
        public string secretAnswer { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public string ip { get; set; }
    }
}
