//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePaperWeb.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber
    {
        public int subscriberID { get; set; }
        public string emailAddress { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string passwordHash { get; set; }
        public string secretquestion { get; set; }
        public string secretans { get; set; }
        public string ipAddress { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> addressID { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<int> newsletter { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
