//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePaperWeb.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber_roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subscriber_roles()
        {
            this.subscribers = new HashSet<subscriber>();
        }
    
        public int roleID { get; set; }
        public string roleDescription { get; set; }
        public System.DateTime createdAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscriber> subscribers { get; set; }
    }
}
