//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePaperWeb.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subscriber()
        {
            this.subscriber_epaper = new HashSet<subscriber_epaper>();
            this.subscriber_print = new HashSet<subscriber_print>();
            this.subscriber_tranx = new HashSet<subscriber_tranx>();
        }
    
        public int subscriberID { get; set; }
        public string emailAddress { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string passwordHash { get; set; }
        public string secretquestion { get; set; }
        public string secretans { get; set; }
        public string ipAddress { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> addressID { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<bool> newsletter { get; set; }
        public System.DateTime createdAt { get; set; }
        public string token { get; set; }
        public Nullable<int> ccHashID { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
    
        public virtual subscriber_address subscriber_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscriber_epaper> subscriber_epaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscriber_print> subscriber_print { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscriber_tranx> subscriber_tranx { get; set; }
    }
}
