//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePaperWeb.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber_tranx
    {
        public int tranxID { get; set; }
        public Nullable<int> subscriberID { get; set; }
        public string emailAddress { get; set; }
        public string cardOwner { get; set; }
        public string cardType { get; set; }
        public Nullable<System.DateTime> tranxDate { get; set; }
        public Nullable<int> rateID { get; set; }
        public string tranxType { get; set; }
        public string orderID { get; set; }
        public Nullable<double> tranxAmount { get; set; }
        public string tranxNotes { get; set; }
        public string ipAddress { get; set; }
    }
}
