//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePaperWeb.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber_address
    {
        public int addressID { get; set; }
        public Nullable<int> subscriberID { get; set; }
        public string emailAddress { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string cityTown { get; set; }
        public string stateParish { get; set; }
        public string zipCode { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
