//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePaperWeb.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber_address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subscriber_address()
        {
            this.subscribers = new HashSet<subscriber>();
        }
    
        public int addressID { get; set; }
        public Nullable<int> subscriberID { get; set; }
        public string emailAddress { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string cityTown { get; set; }
        public string stateParish { get; set; }
        public string zipCode { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscriber> subscribers { get; set; }
    }
}
